@tool
## Spawns scene instances in the editor for tiles carrying a scene path in custom data.
## Editor-time twin of TileSpawner (which spawns at runtime). Mirrors the
## TileCollisionGenerator "generate" button workflow so placed scenes are saved into the
## scene file.
class_name TileSceneGenerator
extends Node

## Tool function to generate scene instances in editor
@export var generate:bool : set = set_generate

@export_group("Clear")
## Step 1: tick to arm clearing. Step 2: tick Clear to remove all generated instances.
@export var confirm_clear:bool = false
## Tool function to remove previously generated instances. Requires confirm_clear first.
@export var clear:bool : set = set_clear

@export_group("")
## TileMapLayer holding the placeholder tiles
@export var tilemap_layer:TileMapLayer

## Node the generated instances are parented to (usually the tilemap_layer)
@export var container:Node2D

## Custom tile data name of String scene path
@export var data_name:String = "scene_path"

## Erase the placeholder cell after spawning so its art doesn't overlap the spawned scene
@export var erase_placeholder:bool = true

## Extra offset added to each spawned instance to align it with the tiling grid.
## The marker atlas tile (block_strip4, 32x32 region) is sized differently than the iso
## wall tiles, so a half-tile correction is usually needed. Tune in the inspector if the
## spawned scene is off; common iso correction is +/- (tile_w/2, tile_h/2).
@export var spawn_offset:Vector2 = Vector2(16, 8)


func set_generate(value:bool)->void:
	if !is_inside_tree():
		return
	if !Engine.is_editor_hint():
		return
	cleanup()
	setup_scenes()


func set_clear(value:bool)->void:
	if !is_inside_tree():
		return
	if !Engine.is_editor_hint():
		return
	if !confirm_clear:
		push_warning("TileSceneGenerator: tick 'Confirm Clear' before clearing.")
		return
	# Disarm so a second clear needs re-confirmation
	confirm_clear = false
	notify_property_list_changed()
	cleanup()


## Free instances previously generated by this node, restoring any erased placeholder cells
func cleanup()->void:
	for child:Node in container.get_children():
		if child.get_meta("generated_by_scene_tile", false) != true:
			continue
		# Restore the placeholder cell so the layout survives a clear/regenerate cycle
		if child.has_meta("source_cell") and child.has_meta("source_id"):
			var _cell:Vector2i = child.get_meta("source_cell")
			var _src:int = child.get_meta("source_id")
			if _src != -1 and tilemap_layer.get_cell_source_id(_cell) == -1:
				tilemap_layer.set_cell(_cell, _src, child.get_meta("source_atlas", Vector2i.ZERO))
		container.remove_child(child)
		child.queue_free()


func setup_scenes()->void:
	# TileSet must expose the scene_path custom data layer
	var _tile_data_count:int = tilemap_layer.tile_set.get_custom_data_layers_count()
	var _tile_data_names:Array[String]
	_tile_data_names.resize(_tile_data_count)
	for i:int in _tile_data_count:
		_tile_data_names[i] = tilemap_layer.tile_set.get_custom_data_layer_name(i)
	if !_tile_data_names.has(data_name):
		return

	# Keep loaded scenes in memory across cells
	var _scene_cache:Dictionary
	var _tiles:Array[Vector2i] = tilemap_layer.get_used_cells()
	for _tile_pos:Vector2i in _tiles:
		var _tile_data:TileData = tilemap_layer.get_cell_tile_data(_tile_pos)
		var _file_path:String = _tile_data.get_custom_data(data_name)
		if _file_path.is_empty():
			continue

		var _scene:PackedScene = _scene_cache.get(_file_path, null)
		if _scene == null:
			_scene = load(_file_path)
			_scene_cache[_file_path] = _scene

		var _instance:Node2D = _scene.instantiate()
		_instance.position = tilemap_layer.map_to_local(_tile_pos) + spawn_offset
		_instance.set_meta("generated_by_scene_tile", true)
		# Record source cell so a later Clear can restore the placeholder tile
		_instance.set_meta("source_cell", _tile_pos)
		_instance.set_meta("source_id", tilemap_layer.get_cell_source_id(_tile_pos))
		_instance.set_meta("source_atlas", tilemap_layer.get_cell_atlas_coords(_tile_pos))
		# Name as <SceneBase><N>, N incrementing from the highest existing in container.
		# Computed before add_child so the new node doesn't count itself.
		var _base:String = _scene.get_state().get_node_name(0)
		_instance.name = _base + str(_next_name_index(_base))
		container.add_child(_instance)
		# owner = scene root so the instance is saved into the scene file
		_instance.owner = owner

		if erase_placeholder:
			tilemap_layer.erase_cell(_tile_pos)


## Lowest integer N (>= 1) such that "<base><N>" is not already used by a sibling
func _next_name_index(base:String)->int:
	var _used:Dictionary
	for child:Node in container.get_children():
		var _name:String = child.name
		if !_name.begins_with(base):
			continue
		var _suffix:String = _name.substr(base.length())
		# bare base name (no number) counts as index 1
		if _suffix.is_empty():
			_used[1] = true
		elif _suffix.is_valid_int():
			_used[_suffix.to_int()] = true
	var _n:int = 1
	while _used.has(_n):
		_n += 1
	return _n
